version: '3.4'

name: guroo

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  postgres:
    image: postgres:15-alpine

  rabbitmq:
    image: rabbitmq:3.13-management

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # Expose pgAdmin's web UI on port 5050
    networks:
      - my_network

volumes:
  postgres_stocksdb:

networks:
  my_network:
  rabbitmq_network:
    driver: bridge
