version: '3.4'

name: guroo

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  postgres:
    image: postgres:15-alpine

  rabbitmq:
    image: rabbitmq:3.13-management

volumes:
  postgres_stocksdb:

networks:
  my_network:
  rabbitmq_network:
    driver: bridge
